apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: weather-app
    type: front-end
  ports:
    - protocol: TCP
      port: 80            # Exposed service port
      targetPort: 8000     # Container port
      nodePort: 30007      # Node port, can be automatically assigned if omitted
  type: NodePort
