name: Kube Manifest Update

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        id: docker_build
        run: |
          docker buildx build --tag hamster01/flask:${{ github.sha }} --load .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push hamster01/flask:${{ github.sha }}

      - name: Update nginx deployment with new image
        run: |
          yq e '.spec.template.spec.containers[0].image = "hamster01/flask:${{ github.sha }}"' -i nginx/deployment.yaml

      - name: Commit and push changes
        run: |
          git config --local user.email "your-email@example.com"
          git config --local user.name "GitHub Action"
          git add ./nginx/deployment.yaml
          git commit -m "Update nginx deployment image to version ${{ github.sha }}"
          # git push
      
